name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * 1,15 * *" # Runs only on default branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@eb53b3ec07136a6ebaed78d8135806da64f7c7e2 # v5
        with:
          name: ivuorinen/docker-php-with-imagick
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          default_branch: main
          tags: "latest,php81"
          cache: ${{ github.event_name != 'schedule' }}
