name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * 1,15 * *' # Runs only on default branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag php-imagick:$(date +%s)
